"""Trading-related models: Signal, Order, Position, Trade, PortfolioSnapshot."""

from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User


class Signal(TimestampMixin, Base):
    """Trading signal generated by AI or strategy."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    symbol: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    signal_type: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # buy, sell, hold
    source: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # ai, strategy, manual
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    entry_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    target_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    stop_loss: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    timeframe: Mapped[str] = mapped_column(String(20), nullable=False, default="1h")
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True
    )
    model_version: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    metadata_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False, server_default="true"
    )
    executed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return f"<Signal(id={self.id}, symbol={self.symbol}, type={self.signal_type})>"


class Order(TimestampMixin, Base):
    """Order model for tracking all order types."""

    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False, index=True
    )
    exchange_order_id: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True
    )
    symbol: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    order_type: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # market, limit, stop_limit
    side: Mapped[str] = mapped_column(
        String(10), nullable=False
    )  # buy, sell
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    price: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    stop_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    filled_quantity: Mapped[float] = mapped_column(
        Numeric(20, 8), default=0, nullable=False, server_default="0"
    )
    average_fill_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", index=True
    )  # pending, open, filled, cancelled, rejected
    time_in_force: Mapped[str] = mapped_column(
        String(20), default="gtc", nullable=False
    )  # gtc, ioc, fok
    is_paper: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False, server_default="true"
    )
    signal_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("signals.id"), nullable=True
    )
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True
    )
    commission: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    commission_asset: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True
    )
    placed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    filled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="orders")

    def __repr__(self) -> str:
        return f"<Order(id={self.id}, symbol={self.symbol}, side={self.side}, status={self.status})>"


class Position(TimestampMixin, Base):
    """Position model for tracking open positions."""

    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False, index=True
    )
    symbol: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    side: Mapped[str] = mapped_column(
        String(10), nullable=False
    )  # long, short
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    entry_price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    current_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    unrealized_pnl: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    realized_pnl: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    leverage: Mapped[float] = mapped_column(
        Float, default=1.0, nullable=False, server_default="1.0"
    )
    liquidation_price: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    margin: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    is_open: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False, server_default="true"
    )
    opened_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    closed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="positions")

    def __repr__(self) -> str:
        return f"<Position(id={self.id}, symbol={self.symbol}, side={self.side}, is_open={self.is_open})>"


class Trade(TimestampMixin, Base):
    """Trade model for completed trades."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False, index=True
    )
    order_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("orders.id"), nullable=True
    )
    position_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("positions.id"), nullable=True
    )
    symbol: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    side: Mapped[str] = mapped_column(
        String(10), nullable=False
    )  # buy, sell
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    fee: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    pnl: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    is_paper: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False, server_default="true"
    )
    executed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="trades")

    def __repr__(self) -> str:
        return f"<Trade(id={self.id}, symbol={self.symbol}, side={self.side}, pnl={self.pnl})>"


class PortfolioSnapshot(TimestampMixin, Base):
    """Portfolio snapshot for historical tracking."""

    __tablename__ = "portfolio_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=False, index=True
    )
    total_value: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    cash_balance: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    positions_value: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    unrealized_pnl: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    realized_pnl: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    total_pnl: Mapped[Optional[float]] = mapped_column(Numeric(20, 8), nullable=True)
    drawdown: Mapped[Optional[float]] = mapped_column(
        Numeric(20, 8), nullable=True
    )
    snapshot_type: Mapped[str] = mapped_column(
        String(20), default="periodic", nullable=False
    )  # periodic, daily, manual

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="portfolio_snapshots")

    def __repr__(self) -> str:
        return f"<PortfolioSnapshot(id={self.id}, user_id={self.user_id}, total_value={self.total_value})>"
