"""
Breakout Strategy
================

Generates trading signals based on breakout principles:
- Identify consolidation patterns
- Detect breakouts above resistance or below support
- Confirm with volume and volatility expansion
- Trade in the direction of the breakout

Strategy Logic:
- BUY when: consolidation detected + price breaks above resistance + volume expansion + volatility expansion
- SELL when: consolidation detected + price breaks below support + volume expansion + volatility expansion
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from trading_engine.indicators.trend import TrendIndicators, TrendResult
from trading_engine.indicators.momentum import MomentumIndicators, MomentumResult
from trading_engine.indicators.volatility import VolatilityIndicators, VolatilityResult
from trading_engine.indicators.structure import StructureIndicators, StructureResult
from trading_engine.regimes.regime_detector import RegimeDetector, MarketRegime, RegimeResult

logger = logging.getLogger(__name__)


@dataclass
class BreakoutSignal:
    """Signal generated by the breakout strategy."""
    action: str  # 'BUY', 'SELL', 'HOLD'
    confidence: float  # 0-1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward: Optional[float] = None
    reasoning: List[str] = None
    metadata: Dict = None

    def __post_init__(self):
        if self.reasoning is None:
            self.reasoning = []
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            "action": self.action,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


class BreakoutStrategy:
    """
    Breakout trading strategy.

    Identifies consolidation patterns and trades the breakout
    with confirmation from volume and volatility.
    """

    # Strategy parameters
    MIN_CONFIDENCE: float = 0.65
    MIN_RISK_REWARD: float = 2.0
    VOLUME_EXPANSION_THRESHOLD: float = 1.5  # Volume must be 1.5x average
    VOLATILITY_EXPANSION_THRESHOLD: float = 1.2  # BB width must expand by 20%
    CONSOLIDATION_MIN_CANDLES: int = 10
    BREAKOUT_CONFIRMATION_PCT: float = 0.3  # Percentage beyond level to confirm

    def __init__(self):
        self.trend_indicators = TrendIndicators()
        self.momentum_indicators = MomentumIndicators()
        self.volatility_indicators = VolatilityIndicators()
        self.structure_indicators = StructureIndicators()
        self.regime_detector = RegimeDetector()

    def generate_signal(self, df: pd.DataFrame, symbol: str = "UNKNOWN") -> BreakoutSignal:
        """
        Generate a trading signal based on breakout logic.

        Args:
            df: OHLCV DataFrame
            symbol: Trading symbol

        Returns:
            BreakoutSignal with action and metadata
        """
        if df.empty or len(df) < 30:
            return BreakoutSignal(
                action="HOLD",
                confidence=0.0,
                reasoning=["Insufficient data for breakout analysis"],
            )

        # Calculate all indicators
        trend = self.trend_indicators.calculate_all(df)
        momentum = self.momentum_indicators.calculate_all(df)
        volatility = self.volatility_indicators.calculate_all(df)
        structure = self.structure_indicators.calculate_all(df)
        regime = self.regime_detector.detect_regime(df, trend, momentum, volatility, structure)

        current_price = df["close"].iloc[-1]

        # Check for bullish breakout
        long_score, long_reasoning = self._evaluate_long_breakout(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Check for bearish breakout
        short_score, short_reasoning = self._evaluate_short_breakout(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Determine signal
        if long_score >= self.MIN_CONFIDENCE and long_score > short_score:
            return self._create_signal(
                "BUY", long_score, long_reasoning, current_price, volatility, structure
            )
        elif short_score >= self.MIN_CONFIDENCE and short_score > long_score:
            return self._create_signal(
                "SELL", short_score, short_reasoning, current_price, volatility, structure
            )

        return BreakoutSignal(
            action="HOLD",
            confidence=max(long_score, short_score),
            reasoning=long_reasoning + short_reasoning + ["No high-confidence breakout signal"],
        )

    def _evaluate_long_breakout(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a long (BUY) breakout."""
        score = 0.0
        reasoning = []

        # 1. Consolidation detection
        if structure.is_consolidating:
            score += 0.2
            reasoning.append("Consolidation pattern detected")
        else:
            reasoning.append("No clear consolidation pattern")

        # 2. Breakout level check
        if structure.breakout_level:
            threshold = structure.breakout_level * (self.BREAKOUT_CONFIRMATION_PCT / 100)
            if current_price > structure.breakout_level + threshold:
                score += 0.3
                reasoning.append(f"Price broke above resistance at {structure.breakout_level:.4f}")
            elif current_price > structure.breakout_level:
                score += 0.15
                reasoning.append("Price near resistance level")
            else:
                reasoning.append("Price below resistance level")

        # 3. Volume expansion
        volume_expansion = self._check_volume_expansion(df)
        if volume_expansion > self.VOLUME_EXPANSION_THRESHOLD:
            score += 0.2
            reasoning.append(f"Volume expansion detected ({volume_expansion:.2f}x average)")
        elif volume_expansion > 1.0:
            score += 0.05
            reasoning.append("Slight volume increase")

        # 4. Volatility expansion
        vol_expansion = self._check_volatility_expansion(df)
        if vol_expansion > self.VOLATILITY_EXPANSION_THRESHOLD:
            score += 0.15
            reasoning.append("Volatility expansion confirmed")

        # 5. Momentum confirmation
        if momentum.rsi and 50 <= momentum.rsi <= 70:
            score += 0.1
            reasoning.append(f"Healthy RSI for breakout ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi > 70:
            score -= 0.1
            reasoning.append(f"Overbought RSI ({momentum.rsi:.1f})")

        if momentum.macd_histogram and momentum.macd_histogram > 0:
            score += 0.05
            reasoning.append("Positive MACD momentum")

        # 6. Regime check
        if regime.regime == MarketRegime.BREAKOUT:
            score += 0.1
            reasoning.append("Breakout regime confirmed")

        return min(1.0, max(0.0, score)), reasoning

    def _evaluate_short_breakout(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a short (SELL) breakout."""
        score = 0.0
        reasoning = []

        # 1. Consolidation detection
        if structure.is_consolidating:
            score += 0.2
            reasoning.append("Consolidation pattern detected")
        else:
            reasoning.append("No clear consolidation pattern")

        # 2. Breakdown level check
        if structure.breakdown_level:
            threshold = structure.breakdown_level * (self.BREAKOUT_CONFIRMATION_PCT / 100)
            if current_price < structure.breakdown_level - threshold:
                score += 0.3
                reasoning.append(f"Price broke below support at {structure.breakdown_level:.4f}")
            elif current_price < structure.breakdown_level:
                score += 0.15
                reasoning.append("Price near support level")
            else:
                reasoning.append("Price above support level")

        # 3. Volume expansion
        volume_expansion = self._check_volume_expansion(df)
        if volume_expansion > self.VOLUME_EXPANSION_THRESHOLD:
            score += 0.2
            reasoning.append(f"Volume expansion detected ({volume_expansion:.2f}x average)")
        elif volume_expansion > 1.0:
            score += 0.05
            reasoning.append("Slight volume increase")

        # 4. Volatility expansion
        vol_expansion = self._check_volatility_expansion(df)
        if vol_expansion > self.VOLATILITY_EXPANSION_THRESHOLD:
            score += 0.15
            reasoning.append("Volatility expansion confirmed")

        # 5. Momentum confirmation
        if momentum.rsi and 30 <= momentum.rsi <= 50:
            score += 0.1
            reasoning.append(f"Healthy RSI for breakdown ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi < 30:
            score -= 0.1
            reasoning.append(f"Oversold RSI ({momentum.rsi:.1f})")

        if momentum.macd_histogram and momentum.macd_histogram < 0:
            score += 0.05
            reasoning.append("Negative MACD momentum")

        # 6. Regime check
        if regime.regime == MarketRegime.BREAKDOWN:
            score += 0.1
            reasoning.append("Breakdown regime confirmed")

        return min(1.0, max(0.0, score)), reasoning

    def _check_volume_expansion(self, df: pd.DataFrame, period: int = 20) -> float:
        """Check if current volume is expanding compared to average."""
        if len(df) < period + 1:
            return 1.0

        current_volume = df["volume"].iloc[-1]
        avg_volume = df["volume"].iloc[-period-1:-1].mean()

        if avg_volume == 0:
            return 1.0

        return current_volume / avg_volume

    def _check_volatility_expansion(self, df: pd.DataFrame, period: int = 20) -> float:
        """Check if volatility is expanding."""
        if len(df) < period * 2:
            return 1.0

        from trading_engine.indicators.volatility import VolatilityIndicators
        vi = VolatilityIndicators()

        recent_bb = vi.bollinger_bands(df["close"].iloc[-period:], period)
        previous_bb = vi.bollinger_bands(df["close"].iloc[-period*2:-period], period)

        if recent_bb["width"] is None or previous_bb["width"] is None or previous_bb["width"] == 0:
            return 1.0

        return recent_bb["width"] / previous_bb["width"]

    def _create_signal(
        self,
        action: str,
        confidence: float,
        reasoning: List[str],
        current_price: float,
        volatility: VolatilityResult,
        structure: StructureResult,
    ) -> BreakoutSignal:
        """Create a complete signal with entry, stop loss, and take profit."""

        # Calculate stop loss
        if volatility.atr:
            if action == "BUY":
                # Stop below the breakout level or 1.5 ATR
                if structure.breakout_level:
                    stop_loss = min(structure.breakout_level * 0.99, current_price - volatility.atr * 1.5)
                else:
                    stop_loss = current_price - volatility.atr * 1.5
            else:
                # Stop above the breakdown level or 1.5 ATR
                if structure.breakdown_level:
                    stop_loss = max(structure.breakdown_level * 1.01, current_price + volatility.atr * 1.5)
                else:
                    stop_loss = current_price + volatility.atr * 1.5
        else:
            stop_pct = 0.02
            stop_loss = current_price * (1 - stop_pct) if action == "BUY" else current_price * (1 + stop_pct)

        # Calculate take profit
        risk = abs(current_price - stop_loss)
        take_profit = current_price + (risk * self.MIN_RISK_REWARD) if action == "BUY" else current_price - (risk * self.MIN_RISK_REWARD)

        risk_reward = abs(take_profit - current_price) / risk if risk > 0 else 0

        reasoning.append(f"Entry: {current_price:.4f}, SL: {stop_loss:.4f}, TP: {take_profit:.4f}")
        reasoning.append(f"Risk/Reward: {risk_reward:.2f}")

        return BreakoutSignal(
            action=action,
            confidence=confidence,
            entry_price=current_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
            reasoning=reasoning,
            metadata={
                "strategy": "breakout",
                "breakout_level": structure.breakout_level,
                "breakdown_level": structure.breakdown_level,
                "is_consolidating": structure.is_consolidating,
            },
        )

    def reset(self) -> None:
        """Reset strategy state."""
        self.trend_indicators.reset()
        self.momentum_indicators.reset()
        self.volatility_indicators.reset()
        self.structure_indicators.reset()
        self.regime_detector.reset()
