"""
Mean Reversion Strategy
=======================

Generates trading signals based on mean reversion principles:
- Only trades in RANGE regime
- Buys when price is at support / oversold
- Sells when price is at resistance / overbought
- Expects price to return to the mean

Strategy Logic:
- BUY when: RANGE regime + price near support + RSI oversold + Bollinger %B near 0
- SELL when: RANGE regime + price near resistance + RSI overbought + Bollinger %B near 1
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from trading_engine.indicators.trend import TrendIndicators, TrendResult
from trading_engine.indicators.momentum import MomentumIndicators, MomentumResult
from trading_engine.indicators.volatility import VolatilityIndicators, VolatilityResult
from trading_engine.indicators.structure import StructureIndicators, StructureResult
from trading_engine.regimes.regime_detector import RegimeDetector, MarketRegime, RegimeResult

logger = logging.getLogger(__name__)


@dataclass
class MeanReversionSignal:
    """Signal generated by the mean reversion strategy."""
    action: str  # 'BUY', 'SELL', 'HOLD'
    confidence: float  # 0-1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward: Optional[float] = None
    reasoning: List[str] = None
    metadata: Dict = None

    def __post_init__(self):
        if self.reasoning is None:
            self.reasoning = []
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            "action": self.action,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


class MeanReversionStrategy:
    """
    Mean reversion trading strategy.

    Only trades in range-bound markets, buying at support and
    selling at resistance with expectation of price returning to mean.
    """

    # Strategy parameters
    MIN_CONFIDENCE: float = 0.65
    MIN_RISK_REWARD: float = 1.5
    RSI_OVERSOLD: float = 30.0
    RSI_OVERBOUGHT: float = 70.0
    BB_OVERSOLD: float = 0.2  # %B below this is oversold
    BB_OVERBOUGHT: float = 0.8  # %B above this is overbought
    SUPPORT_DISTANCE_PCT: float = 2.0  # Max distance from support (%)
    RESISTANCE_DISTANCE_PCT: float = 2.0  # Max distance from resistance (%)

    def __init__(self):
        self.trend_indicators = TrendIndicators()
        self.momentum_indicators = MomentumIndicators()
        self.volatility_indicators = VolatilityIndicators()
        self.structure_indicators = StructureIndicators()
        self.regime_detector = RegimeDetector()

    def generate_signal(self, df: pd.DataFrame, symbol: str = "UNKNOWN") -> MeanReversionSignal:
        """
        Generate a trading signal based on mean reversion logic.

        Args:
            df: OHLCV DataFrame
            symbol: Trading symbol

        Returns:
            MeanReversionSignal with action and metadata
        """
        if df.empty or len(df) < 30:
            return MeanReversionSignal(
                action="HOLD",
                confidence=0.0,
                reasoning=["Insufficient data for mean reversion analysis"],
            )

        # Calculate all indicators
        trend = self.trend_indicators.calculate_all(df)
        momentum = self.momentum_indicators.calculate_all(df)
        volatility = self.volatility_indicators.calculate_all(df)
        structure = self.structure_indicators.calculate_all(df)
        regime = self.regime_detector.detect_regime(df, trend, momentum, volatility, structure)

        current_price = df["close"].iloc[-1]

        # Mean reversion only works in range regime
        if regime.regime != MarketRegime.RANGE:
            return MeanReversionSignal(
                action="HOLD",
                confidence=0.0,
                reasoning=[f"Mean reversion requires RANGE regime, current: {regime.regime.value}"],
            )

        # Check for bullish mean reversion (buy at support)
        long_score, long_reasoning = self._evaluate_long_reversion(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Check for bearish mean reversion (sell at resistance)
        short_score, short_reasoning = self._evaluate_short_reversion(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Determine signal
        if long_score >= self.MIN_CONFIDENCE and long_score > short_score:
            return self._create_signal(
                "BUY", long_score, long_reasoning, current_price, volatility, structure
            )
        elif short_score >= self.MIN_CONFIDENCE and short_score > long_score:
            return self._create_signal(
                "SELL", short_score, short_reasoning, current_price, volatility, structure
            )

        return MeanReversionSignal(
            action="HOLD",
            confidence=max(long_score, short_score),
            reasoning=long_reasoning + short_reasoning + ["No high-confidence mean reversion signal"],
        )

    def _evaluate_long_reversion(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a long (BUY) mean reversion."""
        score = 0.0
        reasoning = []

        # 1. Range regime confirmation
        if regime.regime == MarketRegime.RANGE:
            score += 0.25
            reasoning.append("Range regime confirmed - suitable for mean reversion")

        # 2. Price near support
        if structure.support_levels:
            nearest_support = None
            for level in structure.support_levels:
                if level.price < current_price:
                    nearest_support = level
                    break

            if nearest_support:
                distance = (current_price - nearest_support.price) / current_price * 100
                if distance < self.SUPPORT_DISTANCE_PCT:
                    score += 0.25
                    reasoning.append(f"Price near support ({nearest_support.price:.4f}, distance: {distance:.2f}%)")
                else:
                    reasoning.append(f"Price far from support (distance: {distance:.2f}%)")
            else:
                reasoning.append("No support level found below current price")
        else:
            reasoning.append("No support levels identified")

        # 3. RSI oversold
        if momentum.rsi and momentum.rsi <= self.RSI_OVERSOLD:
            score += 0.2
            reasoning.append(f"RSI oversold ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi <= 40:
            score += 0.1
            reasoning.append(f"RSI approaching oversold ({momentum.rsi:.1f})")
        else:
            reasoning.append(f"RSI not oversold ({momentum.rsi:.1f})" if momentum.rsi else "RSI unavailable")

        # 4. Bollinger %B near 0
        if volatility.bb_position is not None:
            if volatility.bb_position <= self.BB_OVERSOLD:
                score += 0.15
                reasoning.append(f"Bollinger %B near lower band ({volatility.bb_position:.2f})")
            elif volatility.bb_position <= 0.3:
                score += 0.05
                reasoning.append(f"Bollinger %B approaching lower band ({volatility.bb_position:.2f})")

        # 5. Momentum turning positive
        if momentum.macd_histogram and momentum.macd_histogram > 0:
            score += 0.1
            reasoning.append("MACD histogram positive - momentum turning")

        # 6. Consolidation strength
        if structure.consolidation_strength > 0.5:
            score += 0.05
            reasoning.append("Strong consolidation pattern")

        return min(1.0, max(0.0, score)), reasoning

    def _evaluate_short_reversion(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a short (SELL) mean reversion."""
        score = 0.0
        reasoning = []

        # 1. Range regime confirmation
        if regime.regime == MarketRegime.RANGE:
            score += 0.25
            reasoning.append("Range regime confirmed - suitable for mean reversion")

        # 2. Price near resistance
        if structure.resistance_levels:
            nearest_resistance = None
            for level in structure.resistance_levels:
                if level.price > current_price:
                    nearest_resistance = level
                    break

            if nearest_resistance:
                distance = (nearest_resistance.price - current_price) / current_price * 100
                if distance < self.RESISTANCE_DISTANCE_PCT:
                    score += 0.25
                    reasoning.append(f"Price near resistance ({nearest_resistance.price:.4f}, distance: {distance:.2f}%)")
                else:
                    reasoning.append(f"Price far from resistance (distance: {distance:.2f}%)")
            else:
                reasoning.append("No resistance level found above current price")
        else:
            reasoning.append("No resistance levels identified")

        # 3. RSI overbought
        if momentum.rsi and momentum.rsi >= self.RSI_OVERBOUGHT:
            score += 0.2
            reasoning.append(f"RSI overbought ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi >= 60:
            score += 0.1
            reasoning.append(f"RSI approaching overbought ({momentum.rsi:.1f})")
        else:
            reasoning.append(f"RSI not overbought ({momentum.rsi:.1f})" if momentum.rsi else "RSI unavailable")

        # 4. Bollinger %B near 1
        if volatility.bb_position is not None:
            if volatility.bb_position >= self.BB_OVERBOUGHT:
                score += 0.15
                reasoning.append(f"Bollinger %B near upper band ({volatility.bb_position:.2f})")
            elif volatility.bb_position >= 0.7:
                score += 0.05
                reasoning.append(f"Bollinger %B approaching upper band ({volatility.bb_position:.2f})")

        # 5. Momentum turning negative
        if momentum.macd_histogram and momentum.macd_histogram < 0:
            score += 0.1
            reasoning.append("MACD histogram negative - momentum turning")

        # 6. Consolidation strength
        if structure.consolidation_strength > 0.5:
            score += 0.05
            reasoning.append("Strong consolidation pattern")

        return min(1.0, max(0.0, score)), reasoning

    def _create_signal(
        self,
        action: str,
        confidence: float,
        reasoning: List[str],
        current_price: float,
        volatility: VolatilityResult,
        structure: StructureResult,
    ) -> MeanReversionSignal:
        """Create a complete signal with entry, stop loss, and take profit."""

        # Calculate stop loss
        if volatility.atr:
            if action == "BUY":
                # Stop below support or 1.5 ATR
                if structure.support_levels:
                    nearest_support = None
                    for level in structure.support_levels:
                        if level.price < current_price:
                            nearest_support = level
                            break
                    if nearest_support:
                        stop_loss = min(nearest_support.price * 0.99, current_price - volatility.atr * 1.5)
                    else:
                        stop_loss = current_price - volatility.atr * 1.5
                else:
                    stop_loss = current_price - volatility.atr * 1.5
            else:
                # Stop above resistance or 1.5 ATR
                if structure.resistance_levels:
                    nearest_resistance = None
                    for level in structure.resistance_levels:
                        if level.price > current_price:
                            nearest_resistance = level
                            break
                    if nearest_resistance:
                        stop_loss = max(nearest_resistance.price * 1.01, current_price + volatility.atr * 1.5)
                    else:
                        stop_loss = current_price + volatility.atr * 1.5
                else:
                    stop_loss = current_price + volatility.atr * 1.5
        else:
            stop_pct = 0.015
            stop_loss = current_price * (1 - stop_pct) if action == "BUY" else current_price * (1 + stop_pct)

        # Calculate take profit (target the mean/middle band)
        if volatility.bb_middle:
            take_profit = volatility.bb_middle
        else:
            risk = abs(current_price - stop_loss)
            take_profit = current_price + (risk * self.MIN_RISK_REWARD) if action == "BUY" else current_price - (risk * self.MIN_RISK_REWARD)

        risk_reward = abs(take_profit - current_price) / abs(current_price - stop_loss) if stop_loss != current_price else 0

        reasoning.append(f"Entry: {current_price:.4f}, SL: {stop_loss:.4f}, TP: {take_profit:.4f}")
        reasoning.append(f"Risk/Reward: {risk_reward:.2f}")

        return MeanReversionSignal(
            action=action,
            confidence=confidence,
            entry_price=current_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
            reasoning=reasoning,
            metadata={
                "strategy": "mean_reversion",
                "bb_middle": volatility.bb_middle,
                "bb_position": volatility.bb_position,
            },
        )

    def reset(self) -> None:
        """Reset strategy state."""
        self.trend_indicators.reset()
        self.momentum_indicators.reset()
        self.volatility_indicators.reset()
        self.structure_indicators.reset()
        self.regime_detector.reset()
