"""
Pullback Strategy
=================

Generates trading signals based on pullback principles:
- Identify established trends
- Wait for price to retrace (pullback)
- Enter when price shows signs of resuming the trend
- Use support/resistance levels for entry confirmation

Strategy Logic:
- BUY when: bullish trend + price pulls back to support + momentum recovers
- SELL when: bearish trend + price pulls back to resistance + momentum recovers
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from trading_engine.indicators.trend import TrendIndicators, TrendResult
from trading_engine.indicators.momentum import MomentumIndicators, MomentumResult
from trading_engine.indicators.volatility import VolatilityIndicators, VolatilityResult
from trading_engine.indicators.structure import StructureIndicators, StructureResult
from trading_engine.regimes.regime_detector import RegimeDetector, MarketRegime, RegimeResult

logger = logging.getLogger(__name__)


@dataclass
class PullbackSignal:
    """Signal generated by the pullback strategy."""
    action: str  # 'BUY', 'SELL', 'HOLD'
    confidence: float  # 0-1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward: Optional[float] = None
    reasoning: List[str] = None
    metadata: Dict = None

    def __post_init__(self):
        if self.reasoning is None:
            self.reasoning = []
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            "action": self.action,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


class PullbackStrategy:
    """
    Pullback trading strategy.

    Identifies pullbacks within established trends and enters
    when price shows signs of resuming the trend direction.
    """

    # Strategy parameters
    MIN_CONFIDENCE: float = 0.6
    MIN_RISK_REWARD: float = 2.0
    MAX_PULLBACK_PERCENT: float = 5.0  # Maximum pullback percentage
    MIN_PULLBACK_PERCENT: float = 0.5  # Minimum pullback percentage
    MOMENTUM_RECOVERY_THRESHOLD: float = 0.3  # MACD histogram must turn positive

    def __init__(self):
        self.trend_indicators = TrendIndicators()
        self.momentum_indicators = MomentumIndicators()
        self.volatility_indicators = VolatilityIndicators()
        self.structure_indicators = StructureIndicators()
        self.regime_detector = RegimeDetector()

    def generate_signal(self, df: pd.DataFrame, symbol: str = "UNKNOWN") -> PullbackSignal:
        """
        Generate a trading signal based on pullback logic.

        Args:
            df: OHLCV DataFrame
            symbol: Trading symbol

        Returns:
            PullbackSignal with action and metadata
        """
        if df.empty or len(df) < 50:
            return PullbackSignal(
                action="HOLD",
                confidence=0.0,
                reasoning=["Insufficient data for pullback analysis"],
            )

        # Calculate all indicators
        trend = self.trend_indicators.calculate_all(df)
        momentum = self.momentum_indicators.calculate_all(df)
        volatility = self.volatility_indicators.calculate_all(df)
        structure = self.structure_indicators.calculate_all(df)
        regime = self.regime_detector.detect_regime(df, trend, momentum, volatility, structure)

        current_price = df["close"].iloc[-1]

        # Check for bullish pullback
        long_score, long_reasoning = self._evaluate_long_pullback(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Check for bearish pullback
        short_score, short_reasoning = self._evaluate_short_pullback(
            df, trend, momentum, volatility, structure, regime, current_price
        )

        # Determine signal
        if long_score >= self.MIN_CONFIDENCE and long_score > short_score:
            return self._create_signal(
                "BUY", long_score, long_reasoning, current_price, volatility, structure
            )
        elif short_score >= self.MIN_CONFIDENCE and short_score > long_score:
            return self._create_signal(
                "SELL", short_score, short_reasoning, current_price, volatility, structure
            )

        return PullbackSignal(
            action="HOLD",
            confidence=max(long_score, short_score),
            reasoning=long_reasoning + short_reasoning + ["No high-confidence pullback signal"],
        )

    def _evaluate_long_pullback(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a long (BUY) pullback."""
        score = 0.0
        reasoning = []

        # 1. Trend must be bullish
        if trend.trend_direction == "bullish":
            score += 0.25
            reasoning.append("Bullish trend established")
        elif trend.trend_direction == "bearish":
            score -= 0.3
            reasoning.append("Bearish trend - not suitable for long pullback")
        else:
            reasoning.append("No clear trend direction")

        # 2. Check if price has pulled back
        pullback_detected, pullback_pct = self._detect_pullback(df, "bullish")
        if pullback_detected:
            if self.MIN_PULLBACK_PERCENT <= pullback_pct <= self.MAX_PULLBACK_PERCENT:
                score += 0.25
                reasoning.append(f"Healthy pullback detected ({pullback_pct:.2f}%)")
            elif pullback_pct > self.MAX_PULLBACK_PERCENT:
                score -= 0.1
                reasoning.append(f"Excessive pullback ({pullback_pct:.2f}%) - trend may be reversing")
            else:
                reasoning.append(f"Minimal pullback ({pullback_pct:.2f}%)")
        else:
            reasoning.append("No pullback detected")

        # 3. Support level reaction
        if structure.support_levels:
            nearest_support = None
            for level in structure.support_levels:
                if level.price < current_price:
                    nearest_support = level
                    break

            if nearest_support:
                distance = (current_price - nearest_support.price) / current_price * 100
                if distance < 2.0:  # Within 2% of support
                    score += 0.2
                    reasoning.append(f"Price near support level ({nearest_support.price:.4f})")

        # 4. Momentum recovery
        if momentum.macd_histogram and momentum.macd_histogram > 0:
            score += 0.15
            reasoning.append("MACD histogram turning positive - momentum recovering")
        elif momentum.macd_histogram and momentum.macd_histogram < 0:
            reasoning.append("MACD histogram still negative")

        if momentum.rsi and 30 <= momentum.rsi <= 60:
            score += 0.1
            reasoning.append(f"RSI in healthy range ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi < 30:
            score -= 0.1
            reasoning.append(f"RSI oversold ({momentum.rsi:.1f}) - may indicate trend reversal")

        # 5. Regime check
        if regime.regime == MarketRegime.TREND_UP:
            score += 0.1
            reasoning.append("Uptrend regime confirmed")

        return min(1.0, max(0.0, score)), reasoning

    def _evaluate_short_pullback(
        self,
        df: pd.DataFrame,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a short (SELL) pullback."""
        score = 0.0
        reasoning = []

        # 1. Trend must be bearish
        if trend.trend_direction == "bearish":
            score += 0.25
            reasoning.append("Bearish trend established")
        elif trend.trend_direction == "bullish":
            score -= 0.3
            reasoning.append("Bullish trend - not suitable for short pullback")
        else:
            reasoning.append("No clear trend direction")

        # 2. Check if price has pulled back
        pullback_detected, pullback_pct = self._detect_pullback(df, "bearish")
        if pullback_detected:
            if self.MIN_PULLBACK_PERCENT <= pullback_pct <= self.MAX_PULLBACK_PERCENT:
                score += 0.25
                reasoning.append(f"Healthy pullback detected ({pullback_pct:.2f}%)")
            elif pullback_pct > self.MAX_PULLBACK_PERCENT:
                score -= 0.1
                reasoning.append(f"Excessive pullback ({pullback_pct:.2f}%) - trend may be reversing")
            else:
                reasoning.append(f"Minimal pullback ({pullback_pct:.2f}%)")
        else:
            reasoning.append("No pullback detected")

        # 3. Resistance level reaction
        if structure.resistance_levels:
            nearest_resistance = None
            for level in structure.resistance_levels:
                if level.price > current_price:
                    nearest_resistance = level
                    break

            if nearest_resistance:
                distance = (nearest_resistance.price - current_price) / current_price * 100
                if distance < 2.0:  # Within 2% of resistance
                    score += 0.2
                    reasoning.append(f"Price near resistance level ({nearest_resistance.price:.4f})")

        # 4. Momentum recovery
        if momentum.macd_histogram and momentum.macd_histogram < 0:
            score += 0.15
            reasoning.append("MACD histogram turning negative - momentum recovering")
        elif momentum.macd_histogram and momentum.macd_histogram > 0:
            reasoning.append("MACD histogram still positive")

        if momentum.rsi and 40 <= momentum.rsi <= 70:
            score += 0.1
            reasoning.append(f"RSI in healthy range ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi > 70:
            score -= 0.1
            reasoning.append(f"RSI overbought ({momentum.rsi:.1f}) - may indicate trend reversal")

        # 5. Regime check
        if regime.regime == MarketRegime.TREND_DOWN:
            score += 0.1
            reasoning.append("Downtrend regime confirmed")

        return min(1.0, max(0.0, score)), reasoning

    def _detect_pullback(self, df: pd.DataFrame, trend_direction: str) -> tuple:
        """
        Detect if a pullback has occurred.

        Returns:
            Tuple of (pullback_detected, pullback_percentage)
        """
        if len(df) < 20:
            return False, 0.0

        # Find the recent extreme in the trend direction
        if trend_direction == "bullish":
            # Find the recent high
            recent_high = df["high"].iloc[-20:].max()
            current_price = df["close"].iloc[-1]
            pullback_pct = ((recent_high - current_price) / recent_high) * 100
            return pullback_pct > 0.1, pullback_pct
        else:
            # Find the recent low
            recent_low = df["low"].iloc[-20:].min()
            current_price = df["close"].iloc[-1]
            pullback_pct = ((current_price - recent_low) / recent_low) * 100
            return pullback_pct > 0.1, pullback_pct

    def _create_signal(
        self,
        action: str,
        confidence: float,
        reasoning: List[str],
        current_price: float,
        volatility: VolatilityResult,
        structure: StructureResult,
    ) -> PullbackSignal:
        """Create a complete signal with entry, stop loss, and take profit."""

        # Calculate stop loss
        if volatility.atr:
            if action == "BUY":
                # Stop below the nearest support or 2 ATR
                if structure.support_levels:
                    nearest_support = None
                    for level in structure.support_levels:
                        if level.price < current_price:
                            nearest_support = level
                            break
                    if nearest_support:
                        stop_loss = min(nearest_support.price * 0.99, current_price - volatility.atr * 2)
                    else:
                        stop_loss = current_price - volatility.atr * 2
                else:
                    stop_loss = current_price - volatility.atr * 2
            else:
                # Stop above the nearest resistance or 2 ATR
                if structure.resistance_levels:
                    nearest_resistance = None
                    for level in structure.resistance_levels:
                        if level.price > current_price:
                            nearest_resistance = level
                            break
                    if nearest_resistance:
                        stop_loss = max(nearest_resistance.price * 1.01, current_price + volatility.atr * 2)
                    else:
                        stop_loss = current_price + volatility.atr * 2
                else:
                    stop_loss = current_price + volatility.atr * 2
        else:
            stop_pct = 0.02
            stop_loss = current_price * (1 - stop_pct) if action == "BUY" else current_price * (1 + stop_pct)

        # Calculate take profit
        risk = abs(current_price - stop_loss)
        take_profit = current_price + (risk * self.MIN_RISK_REWARD) if action == "BUY" else current_price - (risk * self.MIN_RISK_REWARD)

        risk_reward = abs(take_profit - current_price) / risk if risk > 0 else 0

        reasoning.append(f"Entry: {current_price:.4f}, SL: {stop_loss:.4f}, TP: {take_profit:.4f}")
        reasoning.append(f"Risk/Reward: {risk_reward:.2f}")

        return PullbackSignal(
            action=action,
            confidence=confidence,
            entry_price=current_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
            reasoning=reasoning,
            metadata={
                "strategy": "pullback",
                "support_levels": [l.price for l in structure.support_levels[:3]],
                "resistance_levels": [l.price for l in structure.resistance_levels[:3]],
            },
        )

    def reset(self) -> None:
        """Reset strategy state."""
        self.trend_indicators.reset()
        self.momentum_indicators.reset()
        self.volatility_indicators.reset()
        self.structure_indicators.reset()
        self.regime_detector.reset()
