"""
Trend Following Strategy
========================

Generates trading signals based on trend-following principles:
- Trade in the direction of the established trend
- Enter on pullbacks or breakouts within the trend
- Use multiple timeframe confirmation
- Respect volatility conditions

Strategy Logic:
- BUY when: bullish regime + bullish EMA structure + positive momentum + acceptable volatility
- SELL when: bearish regime + bearish EMA structure + negative momentum + acceptable volatility
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from trading_engine.indicators.trend import TrendIndicators, TrendResult
from trading_engine.indicators.momentum import MomentumIndicators, MomentumResult
from trading_engine.indicators.volatility import VolatilityIndicators, VolatilityResult
from trading_engine.indicators.structure import StructureIndicators, StructureResult
from trading_engine.regimes.regime_detector import RegimeDetector, MarketRegime, RegimeResult

logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by the trend following strategy."""
    action: str  # 'BUY', 'SELL', 'HOLD'
    confidence: float  # 0-1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward: Optional[float] = None
    reasoning: List[str] = None
    metadata: Dict = None

    def __post_init__(self):
        if self.reasoning is None:
            self.reasoning = []
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            "action": self.action,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


class TrendFollowingStrategy:
    """
    Trend following trading strategy.

    This strategy identifies established trades in the direction of the trend
    with confirmation from multiple indicators.
    """

    # Strategy parameters
    MIN_CONFIDENCE: float = 0.6
    MIN_RISK_REWARD: float = 1.5
    MAX_ATR_PERCENTAGE: float = 3.0  # Don't trade if ATR% is too high
    TREND_STRENGTH_THRESHOLD: float = 20.0  # Minimum ADX for trend

    def __init__(self):
        self.trend_indicators = TrendIndicators()
        self.momentum_indicators = MomentumIndicators()
        self.volatility_indicators = VolatilityIndicators()
        self.structure_indicators = StructureIndicators()
        self.regime_detector = RegimeDetector()

    def generate_signal(self, df: pd.DataFrame, symbol: str = "UNKNOWN") -> StrategySignal:
        """
        Generate a trading signal based on trend following logic.

        Args:
            df: OHLCV DataFrame
            symbol: Trading symbol

        Returns:
            StrategySignal with action and metadata
        """
        if df.empty or len(df) < 50:
            return StrategySignal(
                action="HOLD",
                confidence=0.0,
                reasoning=["Insufficient data for trend analysis"],
            )

        # Calculate all indicators
        trend = self.trend_indicators.calculate_all(df)
        momentum = self.momentum_indicators.calculate_all(df)
        volatility = self.volatility_indicators.calculate_all(df)
        structure = self.structure_indicators.calculate_all(df)
        regime = self.regime_detector.detect_regime(df, trend, momentum, volatility, structure)

        current_price = df["close"].iloc[-1]

        # Evaluate long conditions
        long_score, long_reasoning = self._evaluate_long_conditions(
            trend, momentum, volatility, structure, regime, current_price
        )

        # Evaluate short conditions
        short_score, short_reasoning = self._evaluate_short_conditions(
            trend, momentum, volatility, structure, regime, current_price
        )

        # Determine signal
        if long_score >= self.MIN_CONFIDENCE and long_score > short_score:
            return self._create_signal(
                "BUY", long_score, long_reasoning, current_price, trend, volatility, structure
            )
        elif short_score >= self.MIN_CONFIDENCE and short_score > long_score:
            return self._create_signal(
                "SELL", short_score, short_reasoning, current_price, trend, volatility, structure
            )

        return StrategySignal(
            action="HOLD",
            confidence=max(long_score, short_score),
            reasoning=long_reasoning + short_reasoning + ["No high-confidence signal"],
        )

    def _evaluate_long_conditions(
        self,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a long (BUY) signal."""
        score = 0.0
        reasoning = []

        # 1. Regime check
        if regime.regime == MarketRegime.TREND_UP:
            score += 0.25
            reasoning.append(f"Bullish regime detected (confidence: {regime.confidence:.2f})")
        elif regime.regime == MarketRegime.RANGE:
            score -= 0.1
            reasoning.append("Range regime - not ideal for trend following")

        # 2. EMA structure
        if trend.trend_direction == "bullish":
            score += 0.25
            reasoning.append("Bullish EMA structure (EMA9 > EMA20 > EMA50)")
        elif trend.trend_direction == "bearish":
            score -= 0.2
            reasoning.append("Bearish EMA structure")

        # 3. Trend strength
        if trend.adx and trend.adx >= self.TREND_STRENGTH_THRESHOLD:
            score += 0.15
            reasoning.append(f"Strong trend (ADX: {trend.adx:.1f})")
        elif trend.adx and trend.adx < 15:
            score -= 0.15
            reasoning.append(f"Weak trend (ADX: {trend.adx:.1f})")

        # 4. Momentum
        if momentum.rsi and 40 <= momentum.rsi <= 70:
            score += 0.1
            reasoning.append(f"Healthy RSI ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi > 70:
            score -= 0.1
            reasoning.append(f"Overbought RSI ({momentum.rsi:.1f})")

        if momentum.macd_histogram and momentum.macd_histogram > 0:
            score += 0.1
            reasoning.append("Positive MACD histogram")

        # 5. Volatility check
        if volatility.atr_percentage and volatility.atr_percentage > self.MAX_ATR_PERCENTAGE:
            score -= 0.15
            reasoning.append(f"Excessive volatility (ATR%: {volatility.atr_percentage:.2f})")
        elif volatility.atr_percentage and volatility.atr_percentage < 1.0:
            score += 0.05
            reasoning.append("Low volatility - favorable for entry")

        # 6. Structure
        if structure.trend_direction == "bullish":
            score += 0.1
            reasoning.append("Bullish market structure")

        return min(1.0, max(0.0, score)), reasoning

    def _evaluate_short_conditions(
        self,
        trend: TrendResult,
        momentum: MomentumResult,
        volatility: VolatilityResult,
        structure: StructureResult,
        regime: RegimeResult,
        current_price: float,
    ) -> tuple:
        """Evaluate conditions for a short (SELL) signal."""
        score = 0.0
        reasoning = []

        # 1. Regime check
        if regime.regime == MarketRegime.TREND_DOWN:
            score += 0.25
            reasoning.append(f"Bearish regime detected (confidence: {regime.confidence:.2f})")
        elif regime.regime == MarketRegime.RANGE:
            score -= 0.1
            reasoning.append("Range regime - not ideal for trend following")

        # 2. EMA structure
        if trend.trend_direction == "bearish":
            score += 0.25
            reasoning.append("Bearish EMA structure (EMA9 < EMA20 < EMA50)")
        elif trend.trend_direction == "bullish":
            score -= 0.2
            reasoning.append("Bullish EMA structure")

        # 3. Trend strength
        if trend.adx and trend.adx >= self.TREND_STRENGTH_THRESHOLD:
            score += 0.15
            reasoning.append(f"Strong trend (ADX: {trend.adx:.1f})")
        elif trend.adx and trend.adx < 15:
            score -= 0.15
            reasoning.append(f"Weak trend (ADX: {trend.adx:.1f})")

        # 4. Momentum
        if momentum.rsi and 30 <= momentum.rsi <= 60:
            score += 0.1
            reasoning.append(f"Healthy RSI ({momentum.rsi:.1f})")
        elif momentum.rsi and momentum.rsi < 30:
            score -= 0.1
            reasoning.append(f"Oversold RSI ({momentum.rsi:.1f})")

        if momentum.macd_histogram and momentum.macd_histogram < 0:
            score += 0.1
            reasoning.append("Negative MACD histogram")

        # 5. Volatility check
        if volatility.atr_percentage and volatility.atr_percentage > self.MAX_ATR_PERCENTAGE:
            score -= 0.15
            reasoning.append(f"Excessive volatility (ATR%: {volatility.atr_percentage:.2f})")
        elif volatility.atr_percentage and volatility.atr_percentage < 1.0:
            score += 0.05
            reasoning.append("Low volatility - favorable for entry")

        # 6. Structure
        if structure.trend_direction == "bearish":
            score += 0.1
            reasoning.append("Bearish market structure")

        return min(1.0, max(0.0, score)), reasoning

    def _create_signal(
        self,
        action: str,
        confidence: float,
        reasoning: List[str],
        current_price: float,
        trend: TrendResult,
        volatility: VolatilityResult,
        structure: StructureResult,
    ) -> StrategySignal:
        """Create a complete signal with entry, stop loss, and take profit."""

        # Calculate stop loss based on ATR
        if volatility.atr:
            if action == "BUY":
                stop_loss = current_price - (volatility.atr * 2)
            else:
                stop_loss = current_price + (volatility.atr * 2)
        else:
            # Fallback to percentage-based stop
            stop_pct = 0.02
            stop_loss = current_price * (1 - stop_pct) if action == "BUY" else current_price * (1 + stop_pct)

        # Calculate take profit based on risk/reward
        risk = abs(current_price - stop_loss)
        take_profit = current_price + (risk * self.MIN_RISK_REWARD) if action == "BUY" else current_price - (risk * self.MIN_RISK_REWARD)

        risk_reward = abs(take_profit - current_price) / risk if risk > 0 else 0

        reasoning.append(f"Entry: {current_price:.4f}, SL: {stop_loss:.4f}, TP: {take_profit:.4f}")
        reasoning.append(f"Risk/Reward: {risk_reward:.2f}")

        return StrategySignal(
            action=action,
            confidence=confidence,
            entry_price=current_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
            reasoning=reasoning,
            metadata={
                "strategy": "trend_following",
                "atr": volatility.atr,
                "atr_percentage": volatility.atr_percentage,
            },
        )

    def reset(self) -> None:
        """Reset strategy state."""
        self.trend_indicators.reset()
        self.momentum_indicators.reset()
        self.volatility_indicators.reset()
        self.structure_indicators.reset()
        self.regime_detector.reset()
